version: '2'
services:
  nginx:
    build: docker/nginx
    ports:
      - 127.0.100.100:80:80
    volumes_from:
      - php_nginx
  php_nginx:
    build: docker/php
    volumes:
      - .:/var/www
  db.expresso.dev:
    image: mariadb
    environment:
      MYSQL_USER: expresso-php
      MYSQL_PASSWORD: expresso-php
      MYSQL_DATABASE: expresso-php
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.100.100:8181:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    links:
      - db.expresso.dev:db
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 127.0.100.100:8025:8025
volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local
