version: '2'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80
    volumes:
      - .:/var/www
  php_nginx:
    build: docker/php
    volumes:
      - .:/var/www
  db:
    image: mariadb
    environment:
      MYSQL_USER: expresso-php
      MYSQL_PASSWORD: expresso-php
      MYSQL_DATABASE: expresso-php
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80
    environment:
      MYSQL_ROOT_PASSWORD: root
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025
  # SOLR
  # Uncomment below block of lines to enable SOLR.
  # solr:
  #   image: solr
  #   ports:
  #    - 8983:8983
  #   entrypoint:
  #    - docker-entrypoint.sh
  #    - solr-precreate
  #    - mycore
  # END SOLR
volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local
