version: '2'
services:
  backend:
    image: debian:jessie
    volumes:
      - .:/var/www
  php_apache:
    build: docker/php
    ports:
      - 80
    volumes_from:
      - backend
  db:
    image: mariadb
    environment:
      MYSQL_USER: expresso-php
      MYSQL_PASSWORD: expresso-php
      MYSQL_DATABASE: expresso-php
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80
    environment:
      MYSQL_ROOT_PASSWORD: root
